---

- name: Restart Grafana
  community.docker.docker_container:
    name: "{{ grafana_container.name }}"
    restart: true
    state: started
    comparisons:
      '*': ignore

- name: Restart labbot
  community.docker.docker_container:
    name: "{{ bot_container.name }}"
    restart: true
    state: started
    comparisons:
      '*': ignore

- name: Restart Prometheus
  community.docker.docker_container:
    name: "{{ prometheus_container.name }}"
    restart: true
    state: started
    comparisons:
      '*': ignore

- name: Reload nginx
  community.docker.docker_container_exec:
    container: "{{ nginx_container.container.Name | replace('/', '') }}"
    command: nginx -s reload

- name: Prune Docker images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false
