---

roles:
  - name: stefangweichinger.ansible_rclone
    version: 0.2.0

collections:
  - name: ansible.posix
    version: 1.6.2
  - name: community.crypto
    version: 2.22.3
  - name: community.docker
    version: 4.0.1
  - name: community.general
    version: 9.5.1
