---

roles:
  - name: stefangweichinger.ansible_rclone
    version: 0.2.2

collections:
  - name: ansible.posix
    version: 2.0.0
  - name: community.crypto
    version: 3.0.0
  - name: community.docker
    version: 4.6.1
  - name: community.general
    version: 11.0.0
  # Not required for base functionality, but I (tigattack) use it in my local host_vars.
  - name: ripplefcl.bwscache
    version: 1.2.1
