---

roles:
  - name: stefangweichinger.ansible_rclone
    version: 0.2.4

collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.crypto
    version: 3.0.5
  - name: community.docker
    version: 4.8.2
  - name: community.general
    version: 11.4.1
  # Not required for base functionality, but I (tigattack) use it in my local host_vars.
  - name: ripplefcl.bwscache
    version: 1.3.0
