---

roles:
  - name: stefangweichinger.ansible_rclone
    version: 0.2.1

collections:
  - name: ansible.posix
    version: 2.0.0
  - name: community.crypto
    version: 2.24.0
  - name: community.docker
    version: 4.3.1
  - name: community.general
    version: 10.2.0
