---

roles:
  - name: stefangweichinger.ansible_rclone
    version: 0.2.1

collections:
  - name: ansible.posix
    version: 2.0.0
  - name: community.crypto
    version: 2.26.0
  - name: community.docker
    version: 4.5.1
  - name: community.general
    version: 10.4.0
  # Not required for base functionality, but I (tigattack) use it in my local host_vars.
  - name: ripplefcl.bwscache
    version: 1.1.0
