---

roles:
  - name: stefangweichinger.ansible_rclone
    version: 0.2.1

collections:
  - name: ansible.posix
    version: 1.6.2
  - name: community.crypto
    version: 2.23.0
  - name: community.docker
    version: 4.3.0
  - name: community.general
    version: 10.2.0
