---

roles:
  - name: stefangweichinger.ansible_rclone
    version: 0.2.0

collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.crypto
    version: 2.21.1
  - name: community.docker
    version: 3.12.1
