---

roles:
  - name: stefangweichinger.ansible_rclone
    version: 0.2.0

collections:
  - name: ansible.posix
    version: 1.6.0
  - name: community.crypto
    version: 2.22.0
  - name: community.docker
    version: 3.12.2
  - name: community.general
    version: 9.4.0
