---

# Creates vars such as `bot_container`, `prometheus_container`, etc. for ease of reference.
- name: Set container facts
  ansible.builtin.set_fact:
    "{{ item.name | replace(labbot_container_name_prefix, '') }}_container": "{{ item }}"
  loop: "{{ labbot_containers }}"
  loop_control:
    label: "{{ item.name }}"
  tags: always

- name: Provision configs
  ansible.builtin.include_tasks:
    file: app_configs.yml
    apply:
      tags: app_configs
  tags: app_configs

- name: Docker deploy
  tags: containers
  block:
    - name: Create Docker network
      community.docker.docker_network:
        name: "{{ item.name }}"
        state: present
      loop: "{{ labbot_containers | selectattr('networks', 'defined') | map(attribute='networks') | default([]) | flatten | unique }}"

    - name: Deploy containers
      community.docker.docker_container: "{{ item }}"
      loop: "{{ labbot_containers }}"
      loop_control:
        label: "{{ item.name }}"
      notify: Prune Docker images

- name: Deploy reverse proxy for Grafana
  ansible.builtin.include_tasks:
    file: proxy_setup.yml
    apply:
      tags: proxy
  tags: proxy

- name: Configure backups
  ansible.builtin.include_tasks:
    file: backup_setup.yml
    apply:
      tags: backup
  tags: backup
  when: labbot_enable_bot_backup

- name: Install SSH keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item.key }}"
    exclusive: false
    comment: "{{ item.comment if item.comment is defined else omit }}"
  loop: "{{ labbot_ssh_keys }}"

# Hacky workaround to occasional memory leaks in Red-DiscordBot
- name: Create bot restart cron entries
  ansible.builtin.cron:
    name: "{{ bot_container.name }} restart schedule"
    cron_file: redbot_restart
    user: root
    special_time: monthly
    job: docker restart {{ bot_container.name }}
