---

- name: Get Cloudflare proxy IPs
  ansible.builtin.uri:
    url: "https://api.cloudflare.com/client/v4/ips"
    method: GET
    return_content: true
    headers:
      accept: application/json
  check_mode: false
  register: labbot_cloudflare_ips

- name: Create NGINX dir
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
    owner: root
    group: root
    state: directory
  loop:
    - "{{ labbot_nginx_conf_path_host }}"
    - "{{ labbot_nginx_dhparam_path_host | dirname }}"

- name: Generate Diffie-Hellman parameters (dhparam)
  community.crypto.openssl_dhparam:
    path: "{{ labbot_nginx_dhparam_path_host }}"
    mode: '0644'
    owner: root
    group: root
    state: present

- name: Check for certificate
  ansible.builtin.stat:
    path: "{{ labbot_certbot_cert_bind | split(':') | first }}/live/{{ labbot_grafana_domain }}/fullchain.pem"
  register: labbot_stat_cert

- name: Deploy NGINX container
  community.docker.docker_container:
    name: "{{ labbot_container_name_prefix }}nginx"
    image: nginx:1.29-alpine
    ports: [80:80, 443:443]
    volumes:
      - "{{ labbot_nginx_conf_path_host }}:/etc/nginx/conf.d:ro"
      - "{{ labbot_certbot_www_bind }}:ro"
      - "{{ labbot_certbot_cert_bind }}:ro"
    networks: [name: web]
  register: labbot_nginx_container
  notify: Prune Docker images

- name: Certbot block
  when: not labbot_stat_cert.stat.exists
  block:
    - name: Template NGINX config for ACME challenge
      ansible.builtin.template:
        src: nginx_grafana.conf.j2
        dest: "{{ labbot_nginx_conf_path_host }}/labbot_grafana.conf"
        mode: '0644'
        owner: root
        group: root
      vars:
        acme_only: true

    - name: Reload nginx
      community.docker.docker_container_exec:
        container: nginx
        command: nginx -s reload

    - name: Run certbot # noqa args[module]
      community.docker.docker_container: "{{ labbot_certbot_container }}"

- name: Template NGINX config
  ansible.builtin.template:
    src: nginx_grafana.conf.j2
    dest: "{{ labbot_nginx_conf_path_host }}/labbot_grafana.conf"
    mode: '0644'
    owner: root
    group: root
  notify: Reload nginx

- name: Install certificate renewal cron schedule
  ansible.builtin.cron:
    name: "Certbot renewal"
    cron_file: certbot_renew
    user: root
    special_time: weekly
    # 2024-07-20: Test is bugged lmao
    # noqa jinja[spacing]
    job: >-
      docker run --rm -it
      --name {{ labbot_certbot_container.name }}
      {%- for volume in labbot_certbot_container.volumes %}
      -v '{{ volume }}'
      {%- endfor %}
      {{ labbot_certbot_container.image }}
      {{ labbot_certbot_container.command }}
      && docker exec {{ labbot_nginx_container.container.Name | replace('/', '') }} nginx -s reload
