---

################## NOTE ##################
# All commented settings must be defined #
#  in host_vars unless otherwise stated  #
##########################################


############ Deployment config ###########

# Parent directory for container config paths
labbot_app_base_dir: /opt

# Prefix for all container names
labbot_container_name_prefix: labbot_

# Suffix for red-discordbot container image tag
# e.g. `-noaudio`
labbot_container_image_tag_suffix: ''

############ Bot config ##################

# Discord bot token for LabBot
# labbot_discord_token: ''


############ Monitoring/web config #######

# labbot_grafana_domain: ''
labbot_grafana_username: labbot_admin
# labbot_grafana_password: ''

labbot_grafana_container_user: "{{ ansible_user_uid }}"
labbot_prometheus_container_user: "{{ ansible_user_uid }}"

# List of dictionaries with keys `username`, `password`, and `password_bcrypt`
# labbot_prometheus_users: []

### EXAMPLE:
# labbot_prometheus_users:
#   - username: admin
#     password: '!CHANGE_ME!'
#     # Hashed version of the password
#     # Can be generated like so: htpasswd -nBC 10 '<password>' | tr -d ':\n'
#     password_bcrypt: '<hash here>'

labbot_prometheus_scrape_interval: 10 # seconds

# Prometheus retention size (e.g. 500MB, 2GB, 1TB). Set to 0 for unlimited.
labbot_prometheus_retention_size: 0

# Whether to bind the prometheus web UI port on the host
# Necessary only for testing/debugging
labbot_prometheus_open_port: false

# Whether to bind the cadvisor web UI port on the host
# Necessary only for testing/debugging
labbot_cadvisor_open_port: false

# Email address to register with LetsEncrypt
# labbot_certbot_letsencrypt_email: ''

# Certbot settings for Grafana SSL certificate
# Whether to run certbot in dry-run mode for testing/debugging.
labbot_certbot_dry_run: false


############ Backup config ###############

# Enable backup
labbot_enable_bot_backup: false

# NOTE: The backup variables below only need to be defined if labbot_enable_bot_backup is true

# Discord webhook URL for backup report
# labbot_backup_report_webhook: ''

# User ID to mention upon backup failure
# labbot_backup_report_mention_user_id: ''

# The backup script uses rclone to upload backups to a remote destination. You must define rclone remote(s) here.
# Backups will be uploaded to ALL defined remotes by default. See `labbot_rclone_backup_remotes` to change this.
# For more information, see https://github.com/stefangweichinger/ansible-rclone#rclone_configs-
# labbot_rclone_configs: []

### EXAMPLE:
# labbot_rclone_configs:
#   - name: backups
#     properties:
#       type: webdav
#       vendor: other
#       url: https://webdav.example.com
#       user: user
#       pass: pa$$w0rd

labbot_rclone_config_location: /root/.config/rclone/labbot_backup_remotes.conf

# Backups will be uploaded to ALL defined remotes if this is unset or an empty list.
# If set, backups will only be uploaded to the specified remotes.
labbot_rclone_backup_remotes: []

### EXAMPLE:
# labbot_rclone_backup_remotes:
#   - backups


############ Misc. config ################

# [OPTIONAL] SSH keys to install on the bot host
# EXAMPLE:
# labbot_ssh_keys:
#   - key: <string or URL>
#     comment: <optional comment>
labbot_ssh_keys: []
