---

###################### NOTE ######################
# All commented settings must be defined in host_vars!
##################################################

# Parent directory for container config paths
labbot_app_base_dir: /opt

# Prefix for all container names
labbot_container_name_prefix: labbot_

# Discord bot token for LabBot
# labbot_discord_token:

# labbot_grafana_domain:
labbot_grafana_username: labbot_admin
# labbot_grafana_password:

labbot_grafana_container_user: "{{ ansible_user_uid }}"
labbot_prometheus_container_user: "{{ ansible_user_uid }}"

# List of dictionaries with keys `username`, `password`, and `password_bcrypt`
labbot_prometheus_users: []

labbot_prometheus_scrape_interval: 10 # seconds

# Whether to bind the prometheus web UI port on the host
# Necessary only for testing/debugging
labbot_prometheus_open_port: false

# Whether to bind the cadvisor web UI port on the host
# Necessary only for testing/debugging
labbot_cadvisor_open_port: false

# Certbot settings for Grafana SSL certificate
# Whether to run certbot in dry-run mode
labbot_certbot_dry_run: false

# Email address to register with LetsEncrypt
# labbot_certbot_letsencrypt_email:


# Enable backup
labbot_enable_bot_backup: false

# NOTE: All backup variables below must be defined ONLY if labbot_enable_bot_backup is true

# Discord webhook URL for backup report
# labbot_backup_report_webhook: ''

# User ID to mention upon backup failure
# labbot_backup_report_mention_user_id: ''

# The backup script uses rclone to upload backups to a remote destination. You must define an rclone remote here.
# For more information, see https://github.com/stefangweichinger/ansible-rclone#rclone_configs-
# labbot_rclone_configs: []

### EXAMPLE:
# labbot_rclone_configs:
#   - name: backups
#     properties:
#       type: webdav
#       vendor: other
#       url: https://webdav.example.com
#       user: user
#       pass: pa$$w0rd


# Misc settings

# [OPTIONAL] SSH keys to install on the bot host
# EXAMPLE:
# labbot_ssh_keys:
#   - key: <string or URL>
#     comment: <optional comment>
labbot_ssh_keys: []
